from app.models import Mapeamento

# fundep
mapa = Mapeamento(
    CODIGO = "",
    NOME = "'Receita x Despesa';'Título do Projeto: ';A3",
    SALDO = "",
    DATA_ASSINATURA = "",
    DATA_VIGENCIA = "",
    DATA_ENCERRAMENTO = "",
    TIPO_CONTRATO = "",
    INSTITUICAO_EXECUTORA = "",
    PROCESSO = "",
    SUBPROCESSO = "",
    COD_PROPOSTA = "",
    PROPOSTA = "",
    OBJETIVOS = "",
    VALOR_APROVADO = "",
    NOME_TP_CONTROLE_SALDO = "",
    GRUPO_GESTORES = "",
    GESTOR_RESP = "",
    COORDENADOR = "",
    PROCEDIMENTO_COMPRA = "",
    TAB_FRETE = "",
    TAB_DIARIAS = "",
    CUSTO_OP = "",
    NOME_FINANCIADOR = "",
    DEPARTAMENTO = "",
    SITUACAO = "",
    BANCO = "",
    AGENCIA_BANCARIA = "",
    CONTA_BANCARIA = "",
    CENTRO_CUSTO = "",
    CONTA_CAIXA = "",
    CATEGORIA_PROJETO = "",
    COD_CONVENIO_CONTA = "",
    COD_STATUS = "",
    IND_SUB_PROJETO = "",
    TIPO_CUSTO_OP = "",
    PROJETO_MAE = "",
    ID_COORDENADOR = "",
    ID_FINANCIADOR = "",
    ID_INSTITUICAO = "",
    ID_DEPARTAMENTO = "",
    NOME_INSTITUICAO = "",
    ID_INSTITUICAO_EXECUTORA = "",
    ID_TIPO = ""
)

mapa.save()