from django.db import models

class Mapeamento(models.Model):
    CODIGO = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    NOME = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    SALDO = models.DecimalField(max_digits=10, decimal_places=2, db_type=models.DB_TYPE_NUMBER)
    DATA_ASSINATURA = models.DateField(db_type=models.DB_TYPE_DATE)
    DATA_VIGENCIA = models.DateField(db_type=models.DB_TYPE_DATE)
    DATA_ENCERRAMENTO = models.DateField(db_type=models.DB_TYPE_DATE)
    TIPO_CONTRATO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    INSTITUICAO_EXECUTORA = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    PROCESSO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    SUBPROCESSO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    COD_PROPOSTA = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    PROPOSTA = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    OBJETIVOS = models.TextField(db_type=models.DB_TYPE_CLOB)
    VALOR_APROVADO = models.DecimalField(max_digits=10, decimal_places=2, db_type=models.DB_TYPE_NUMBER)
    NOME_TP_CONTROLE_SALDO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    GRUPO_GESTORES = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    GESTOR_RESP = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    COORDENADOR = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    PROCEDIMENTO_COMPRA = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    TAB_FRETE = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    TAB_DIARIAS = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    CUSTO_OP = models.DecimalField(max_digits=10, decimal_places=2, db_type=models.DB_TYPE_NUMBER)
    NOME_FINANCIADOR = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    DEPARTAMENTO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    SITUACAO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    BANCO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    AGENCIA_BANCARIA = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    CONTA_BANCARIA = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    CENTRO_CUSTO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    CONTA_CAIXA = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    CATEGORIA_PROJETO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    COD_CONVENIO_CONTA = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    COD_STATUS = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    IND_SUB_PROJETO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    TIPO_CUSTO_OP = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    PROJETO_MAE = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    ID_COORDENADOR = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    ID_FINANCIADOR = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    ID_INSTITUICAO = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    ID_DEPARTAMENTO = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    NOME_INSTITUICAO = models.CharField(max_length=200, db_type=models.DB_TYPE_VARCHAR)
    ID_INSTITUICAO_EXECUTORA = models.IntegerField(db_type=models.DB_TYPE_NUMBER)
    ID_TIPO = models.IntegerField(db_type=models.DB_TYPE_NUMBER)

class Template(models.Model):
    nome_template = models.CharField(max_length=200)
    endereco_template = models.CharField(max_length=200)
    mapeamento = models.ForeignKey(Mapeamento, on_delete=models.CASCADE)

class Report(models.Model):
    titulo = models.CharField(max_length=200)
    descricao = models.CharField(max_length=200)
    tipo_erro = models.CharField(max_length=200)
    id_projeto = models.CharField(max_length=200)
    nome_usuario = models.CharField(max_length=200)

class Export(models.Model):
    data_export = models.DateTimeField(auto_now_add=True)
    formato = models.CharField(max_length=200)
    nome_template = models.CharField(max_length=200)
    nome_usuario = models.CharField(max_length=200)
    id_projeto = models.CharField(max_length=200)
