# Generated by Django 4.2.5 on 2023-10-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapeamentoConveniar',
            new_name='Lancamento',
        ),
    ]
