# Generated by Django 4.2.4 on 2024-02-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='tag',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
