# Generated by Django 4.2.4 on 2024-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_useractivity_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
